# Generated by Django 2.1.1 on 2018-11-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lear_post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='learn_reply',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post_reply',
            options={},
        ),
    ]
